platform :ios, '5.0'

# BPKit contains useful code that is scattered throughout the boilerplate
# classes. Feel free to remove it and edit the code if you want.
pod 'BPKit', :git => 'git://github.com/NSBoilerplate/BPKit', :tag => '0.0.1'

pod 'BlocksKit', '1.8.1'
pod 'SSToolkit', '1.0.2'
pod 'CocoaLumberjack', '1.6'
pod 'Reachability', '3.1.0'
pod 'SVProgressHUD', '0.9'
pod 'AFNetworking', '1.1.0'
pod 'UISS', '1.1.0'
pod 'IAPValidation', '0.0.1'
pod 'IAPManager', '0.2.0'

target :KIFTests, :exclusive => false do
    pod 'KIF'
end

target :KiwiTests, :exclusive => true do
    pod 'Kiwi'
    pod 'AFHTTPRequestOperationLogger'
end


